E-mail_Management_MVC/Models/Business/BusinessInputModel.cs
using E_mail_Management_Domain.Entities;
using E_mail_Management_MVC.Models.BusinessEmail;
using System.ComponentModel.DataAnnotations;

namespace E_mail_Management_MVC.Models.Business
{
    public class BusinessInputModel
    {
        [Required(ErrorMessage = "O Nome do Parceiro é Obrigatório.")]
        public string? BusinessName { get; set; }
        public bool BusinessNNI { get; set; }
        public bool Active { get; set; }
        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public DateTime CanceledAt { get; set; }
        public List<BusinessEmailViewModel>? Emails { get; set; } = new List<BusinessEmailViewModel>();
    }
}

E-mail_Management_MVC/Models/Business/BusinessViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace E_mail_Management_MVC.Models.Business
{
    public class BusinessViewModel
    {
        
        public int BusinessId { get; set; }
        public string? BusinessName { get; set; }
        public bool BusinessNNI { get; set; }
        public bool Active { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime CanceledAt { get; set; }
    }
}

E-mail_Management_MVC/Models/BusinessEmail/BusinessEmailViewModel.cs
namespace E_mail_Management_MVC.Models.BusinessEmail
{
    public class BusinessEmailViewModel
    {
        public int BusinessEmailId { get; private set; }
        public string? Email { get; private set; }
    }
}

E-mail_Management_MVC/Models/BusinessEmailViewModel.cs
namespace E_mail_Management_MVC.Models
{
    public class BusinessEmailViewModel
    {
        public int BusinessEmailId { get; private set; }
        public string? Email { get; private set; }
    }
}

E-mail_Management_MVC/Models/BusinessInputModel.cs
using E_mail_Management_Domain.Entities;
using System.ComponentModel.DataAnnotations;

namespace E_mail_Management_MVC.Models
{
    public class BusinessInputModel
    {
        [Required(ErrorMessage = "O Nome do Parceiro é Obrigatório.")]
        public string? BusinessName { get; set; }
        public bool BusinessNNI { get; set; }
        public bool Active { get; set; }
        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public DateTime CanceledAt { get; set; }
        public List<BusinessEmailViewModel>? Emails { get; set; } = new List<BusinessEmailViewModel>();
    }
}

E-mail_Management_MVC/Models/ErrorViewModel.cs
namespace E_mail_Management_MVC.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

E-mail_Management_MVC/Controllers/BusinessController.cs
using AutoMapper;
using E_mail_Management_Domain.Entities;
using E_mail_Management_Domain.Interfaces;
using E_mail_Management_Infrastructure.Context;
using E_mail_Management_MVC.Models.Business;
using Microsoft.AspNetCore.Mvc;

namespace E_mail_Management_MVC.Controllers
{
    public class BusinessController : Controller
    {
        private readonly IBusinessRepository _Businessrepository;
        private readonly IMapper _mapper;
        public BusinessController(IBusinessRepository repository, IMapper mapper)
        {
            _Businessrepository = repository;
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            var business = _Businessrepository.GetAll();
            List<BusinessViewModel> businessVM = _mapper.Map<List<BusinessViewModel>>(business);
            return View(businessVM);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(BusinessInputModel businessModel)
        {
            //VERIFICAR SE O MÓDEL ESTÁ VÁLIDO
            if (!ModelState.IsValid) { return View(businessModel); }
            var model = _mapper.Map<BusinessInputModel, Business>(businessModel);
            _Businessrepository.Add(model);
            return RedirectToAction("Index");
        }
        public IActionResult Details(int id)
        {
            var business = _Businessrepository.GetById(id);
            if (business == null) { return RedirectToAction("Index"); }
            var model = _mapper.Map<Business, BusinessViewModel>(business);
            return View(model);
        }
        [HttpPost]
        public IActionResult Details(BusinessViewModel businessModel)
        {
            //VERIFICAR SE O MÓDEL ESTÁ VÁLIDO
            if (!ModelState.IsValid) { return View(businessModel); }
            var model = _mapper.Map<BusinessViewModel, Business>(businessModel);
            _Businessrepository.Update(model);
            return RedirectToAction("Index");
        }
    }
}

E-mail_Management_MVC/Controllers/HomeController.cs
using E_mail_Management_MVC.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace E_mail_Management_MVC.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

E-mail_Management_MVC/Views/Business/Create.cshtml
@model E_mail_Management_MVC.Models.Business.BusinessInputModel
@{
    ViewData["Title"] = "Create Business";
}

<div class="container-fluid mb-4">
    <a class="btn btn-outline-secondary mb-1" asp-action="Index" asp-controller="Business" asp-area=""><i class="fa fa-arrow-left"></i> Lista de Parceiros </a>
    <!-- Page Heading -->
    <div class="card ">
        <div class="card-header bg-secondary">
            <h4 class="card-title text-white">Criar Parceiro</h4>
        </div>
        <div class="card-body ">
            <form asp-controller="Business" asp-action="Create">
                <div class="mb-2">
                    <label>Parceiro</label>
                    <input type="text" asp-for="BusinessName" class="form-control" />
                    <span asp-validation-for="BusinessName" class="text-danger"></span>
                </div>
                <div class="mb-2">
                    <label>Ativo?</label>
                    <input type="checkbox" asp-for="Active" />
                </div>
                <div class="mb-2">
                    <label>NNI?</label>
                    <input type="checkbox" asp-for="BusinessNNI" />
                </div>


                <div class="mb-2">
                    <button type="submit" class="btn btn-secondary">Add Parceiro</button>
                </div>
            </form>
        </div>


    </div>



</div>

E-mail_Management_MVC/Views/Business/Details.cshtml
@model E_mail_Management_MVC.Models.Business.BusinessViewModel
@{
    ViewData["Title"] = "Details Business";
}
<div class="container-fluid mb-4">
    <a class="btn btn-outline-secondary mb-1" asp-action="Index" asp-controller="Business" asp-area=""><i class="fa fa-arrow-left"></i> Lista de Parceiros </a>
    <!-- Page Heading -->
    <div class="card ">
        <div class="card-header bg-secondary">
            <h4 class="card-title text-white">Editar Parceiro</h4>
        </div>
        <div class="card-body ">
            
            <form asp-controller="Business" asp-action="Details">
                <input type="hidden" asp-for="BusinessId" />
                <div class="mb-2">
                    <label>Parceiro</label>
                    <input type="text" asp-for="BusinessName" class="form-control" />
                    <span asp-validation-for="BusinessName" class="text-danger"></span>
                </div>
                <div class="mb-2">
                    <label>Ativo?</label>
                    <input type="checkbox" asp-for="Active" />
                </div>
                <div class="mb-2">
                    <label>NNI?</label>
                    <input type="checkbox" asp-for="BusinessNNI" />
                </div>


                <div class="mb-2">
                    <button type="submit" class="btn btn-secondary">Salvar Alterações</button>
                </div>
            </form>
        </div>


    </div>



</div>

E-mail_Management_MVC/Views/Business/Index.cshtml
@model List<E_mail_Management_MVC.Models.Business.BusinessViewModel>
@{
    ViewData["Title"] = "Index";
}
<!-- Begin Page Content -->
<div class="container-fluid mb-4">
    <a class="btn btn-outline-secondary mb-1" asp-action="Create" asp-controller="Business" asp-area=""><i class="fa fa-user-plus"></i> Add Parceiro</a>
    <!-- Page Heading -->
    <div class="card">
        <div class="card-header bg-secondary">
            <h4 class="card-title text-white">Lista de Parceiros</h4>
        </div>
        <div class="card-body">
            <table class="table table-striped table-hover" id="myTable">
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Nome</th>
                        <th>NNI</th>
                        <th>Cadastro</th>
                        <th>Status</th>
                        <th>Ações</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var parc in Model)
                    {
                        <tr>
                            <td>@parc.BusinessId</td>
                            <td>@parc.BusinessName</td>
                            <td>@parc.BusinessNNI</td>
                            <td>@parc.CreatedAt</td>
                            <td>@parc.Active</td>
                            <td>
                                <a class="btn btn-outline-dark m-1"
                               asp-action="Details"
                               asp-controller="Business"
                               asp-route-id="@parc.BusinessId">
                                    <i class="fa fa-key"></i>
                                </a>
                                <a class="btn btn-outline-dark m-1"
                               asp-action=""
                               asp-controller=""
                               asp-route-id="@parc.BusinessId">
                                    <i class="fa fa-key"></i>
                                </a>
                                <a class="btn btn-danger m-1"
                               asp-action=""
                               asp-controller=""
                               asp-route-id="@parc.BusinessId">
                                    <i class="fa fa-trash"></i>
                                </a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>


    </div>



</div>

E-mail_Management_MVC/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

E-mail_Management_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - E-mail Management</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/E_mail_Management_MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">E-mail Management</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Business" asp-action="Index">Parceiros</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; E-mail Management - @DateTime.Now.Year - Júlio C. Mesquita.</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>